/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Triforce.intrefaces;

import br.com.Triforce.model.ClienteRegistro;
import br.com.Triforce.model.CodigoExcluidoRegistro;
import br.com.Triforce.model.ProdutoEstoque;
import br.com.Triforce.model.VendaRegistro;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author a145292
 */
public class EfetuarVenda extends Geral {

    /**
     * Creates new form EfetuarVenda
     */
    private ProdutoEstoque prod;
    private ClienteRegistro cli;
    private CodigoExcluidoRegistro ex;
    private VendaTableModel model;
    private VendaRegistro vend;

    public EfetuarVenda(ProdutoEstoque prod, ClienteRegistro cli, CodigoExcluidoRegistro ex, VendaRegistro vend) {
        initComponents();
        this.prod = prod;
        this.cli = cli;
        this.vend = vend;
        this.ex = ex;

        model = new VendaTableModel(vend);
        tab_venda.setModel(model);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                vend.salvar();// serve para quando fechar a janela, salvar meu arquivo
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_efetuarvenda = new javax.swing.JLabel();
        btn_consultarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_venda = new javax.swing.JTable();
        btn_consultarcliente = new javax.swing.JButton();
        lbl_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        txt_cliente = new javax.swing.JTextField();
        lbl_cliente = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_realizarvenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        data_choose = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Vendas");
        setMinimumSize(new java.awt.Dimension(700, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_efetuarvenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_efetuarvenda.setText("Efetuar Venda");
        getContentPane().add(lbl_efetuarvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 11, -1, -1));

        btn_consultarProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_consultarProd.setText("Consultar Produto");
        btn_consultarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarProdMouseClicked(evt);
            }
        });
        getContentPane().add(btn_consultarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        tab_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Valor", "Quantidade", "Autor", "Categoria", "Volume", "DtaLco"
            }
        ));
        jScrollPane1.setViewportView(tab_venda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 219, 631, 308));

        btn_consultarcliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_consultarcliente.setText("Consultar Cliente");
        btn_consultarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarclienteMouseClicked(evt);
            }
        });
        getContentPane().add(btn_consultarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, -1));

        lbl_produto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_produto.setText("Produto:");
        getContentPane().add(lbl_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(txt_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 91, -1));
        getContentPane().add(txt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 91, -1));

        lbl_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cliente.setText("Cliente:");
        getContentPane().add(lbl_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 85, -1));

        btn_realizarvenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_realizarvenda.setText("Realizar Venda");
        btn_realizarvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_realizarvendaMouseClicked(evt);
            }
        });
        btn_realizarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_realizarvendaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_realizarvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 185, 142, -1));

        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txt_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, -1));
        getContentPane().add(data_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        jLabel2.setText("Data Venda: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_consultarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarclienteMouseClicked
        abreJanela(new ConsultarCliente(cli, ex), 0);
    }//GEN-LAST:event_btn_consultarclienteMouseClicked

    private void btn_consultarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarProdMouseClicked
        abreJanela(new ConsultarProduto(prod, ex), 0);
    }//GEN-LAST:event_btn_consultarProdMouseClicked

    private void btn_realizarvendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_realizarvendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_realizarvendaMouseClicked

    private void btn_realizarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_realizarvendaActionPerformed
        // TODO add your handling code here:

        if (prod.verificaKey(Integer.parseInt(txt_produto.getText())) == 1
                && cli.verificaKey(Integer.parseInt(txt_cliente.getText())) == 1
                && prod.getSaldo(Integer.parseInt(txt_produto.getText())) - Integer.parseInt(txt_quantidade.getText()) > 0) {
            Object[] options = {"Sim", "Não"};
            int i = JOptionPane.showOptionDialog(null,
                    "Tem certeza que deseja efetuar a venda ?\n"
                    + "Titulo: " + prod.getTitulo(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "Autor: " + prod.getAutor(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "DataLcto: " + prod.getData(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "Categoria: " + prod.getCategoria(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "Preço: " + prod.getPreco(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "Volume: " + prod.getVolume(Integer.parseInt(txt_produto.getText())) + "\n"
                    + "Quantidade: " + Integer.parseInt(txt_quantidade.getText()) + "\n"
                    + "Valor Total: " + Integer.parseInt(txt_quantidade.getText()) * prod.getPreco(Integer.parseInt(txt_produto.getText())) + "\n", "Efetuar Venda",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    options, options[0]);
            if (i == JOptionPane.YES_OPTION) {
                String data = new SimpleDateFormat("dd/MM/yyyy").format(data_choose.getDate());
                vend.adicionaVenda(vend.retornoMap() + 1,
                        Integer.parseInt(txt_cliente.getText()),
                        Integer.parseInt(txt_produto.getText()),
                        Integer.parseInt(txt_quantidade.getText()),
                        Integer.parseInt(txt_quantidade.getText()) * prod.getPreco(Integer.parseInt(txt_produto.getText())),
                        data);
                prod.setSaldo(Integer.parseInt(txt_produto.getText()), prod.getSaldo(Integer.parseInt(txt_produto.getText())) - Integer.parseInt(txt_quantidade.getText()));
                JOptionPane.showMessageDialog(rootPane, "Venda Efetuada com sucesso!");
                prod.salvar();
                ex.salvar();
                model = new VendaTableModel(vend);
                tab_venda.setModel(model);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Codigo Inexistente ou Quantidade Insuficiente!");
        }

    }//GEN-LAST:event_btn_realizarvendaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultarProd;
    private javax.swing.JButton btn_consultarcliente;
    private javax.swing.JButton btn_realizarvenda;
    private javax.swing.JButton btn_voltar;
    private com.toedter.calendar.JDateChooser data_choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_efetuarvenda;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JTable tab_venda;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_produto;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
