/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Triforce.intrefaces;

import br.com.Triforce.model.ClienteRegistro;
import br.com.Triforce.model.CodigoExcluidoRegistro;
import br.com.Triforce.model.FornecedorRegistro;
import br.com.Triforce.model.FuncionarioRegistro;
import br.com.Triforce.model.PedidoRegistro;
import br.com.Triforce.model.ProdutoEstoque;
import br.com.Triforce.model.VendaRegistro;

/**
 *
 * @author angelo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ProdutoEstoque prod;
    private FornecedorRegistro forReg;
    private FuncionarioRegistro funReg;
    private ClienteRegistro cliReg;
    private PedidoRegistro reg;
    private CodigoExcluidoRegistro ex;
    private VendaRegistro vend;

    public Principal(ProdutoEstoque prod, FornecedorRegistro forReg, FuncionarioRegistro funReg, ClienteRegistro cliReg, PedidoRegistro reg, CodigoExcluidoRegistro ex, VendaRegistro vend) {
        initComponents();

        this.prod = prod;
        this.forReg = forReg;
        this.funReg = funReg;
        this.cliReg = cliReg;
        this.reg = reg;
        this.ex = ex;
        this.vend = vend;

        if (ex.verificaMap(0) == 0) {
            ex.adicionarExcluidos(0, 0, 0, 0, 0, 0, 0);
            ex.salvar();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bar_Principal = new javax.swing.JMenuBar();
        op_Arquivos = new javax.swing.JMenu();
        op_Cadastros = new javax.swing.JMenu();
        op_Produtos = new javax.swing.JMenuItem();
        op_Funcionarios = new javax.swing.JMenuItem();
        op_Cliente = new javax.swing.JMenuItem();
        op_Fornecedor = new javax.swing.JMenuItem();
        op_Acoes = new javax.swing.JMenu();
        op_Venda = new javax.swing.JMenuItem();
        op_Pedido = new javax.swing.JMenuItem();
        op_Estoque = new javax.swing.JMenuItem();

        setTitle("Triforce");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/8105415.png"))); // NOI18N

        op_Arquivos.setText("Arquivos");

        op_Cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-5.png"))); // NOI18N
        op_Cadastros.setText("Cadastros");

        op_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        op_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-4.png"))); // NOI18N
        op_Produtos.setText("Produtos");
        op_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_ProdutosActionPerformed(evt);
            }
        });
        op_Cadastros.add(op_Produtos);

        op_Funcionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        op_Funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-3.png"))); // NOI18N
        op_Funcionarios.setText("Funcionários");
        op_Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_FuncionariosActionPerformed(evt);
            }
        });
        op_Cadastros.add(op_Funcionarios);

        op_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        op_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-1.png"))); // NOI18N
        op_Cliente.setText("Cliente");
        op_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_ClienteActionPerformed(evt);
            }
        });
        op_Cadastros.add(op_Cliente);

        op_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        op_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-2.png"))); // NOI18N
        op_Fornecedor.setText("Fornecedor");
        op_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_FornecedorActionPerformed(evt);
            }
        });
        op_Cadastros.add(op_Fornecedor);

        op_Arquivos.add(op_Cadastros);

        bar_Principal.add(op_Arquivos);

        op_Acoes.setText("Ações");

        op_Venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        op_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-6.png"))); // NOI18N
        op_Venda.setText("Realizar Venda");
        op_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_VendaActionPerformed(evt);
            }
        });
        op_Acoes.add(op_Venda);

        op_Pedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        op_Pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-8.png"))); // NOI18N
        op_Pedido.setText("Pedido de Compra");
        op_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_PedidoActionPerformed(evt);
            }
        });
        op_Acoes.add(op_Pedido);

        op_Estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        op_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/Untitled-9.png"))); // NOI18N
        op_Estoque.setText("Estoque");
        op_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_EstoqueActionPerformed(evt);
            }
        });
        op_Acoes.add(op_Estoque);

        bar_Principal.add(op_Acoes);

        setJMenuBar(bar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 600, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 327, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getAccessibleContext().setAccessibleName("principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_ProdutosActionPerformed
        new Geral().abreJanela(new ConsultarProduto(prod, ex), 0);
    }//GEN-LAST:event_op_ProdutosActionPerformed

    private void op_FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_FuncionariosActionPerformed
        new Geral().abreJanela(new ConsultarFuncionario(funReg, ex), 0);
    }//GEN-LAST:event_op_FuncionariosActionPerformed

    private void op_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_ClienteActionPerformed
        new Geral().abreJanela(new ConsultarCliente(cliReg, ex), 0);
    }//GEN-LAST:event_op_ClienteActionPerformed

    private void op_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_FornecedorActionPerformed
        new Geral().abreJanela(new ConsultarFornecedor(forReg, ex), 0);
    }//GEN-LAST:event_op_FornecedorActionPerformed

    private void op_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_VendaActionPerformed
        new Geral().abreJanela(new EfetuarVenda(prod, cliReg, ex, vend), 0);
    }//GEN-LAST:event_op_VendaActionPerformed

    private void op_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_PedidoActionPerformed
        new Geral().abreJanela(new ConsultarPedido(prod, forReg, reg, ex), 0);
    }//GEN-LAST:event_op_PedidoActionPerformed

    private void op_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_EstoqueActionPerformed
        new Geral().abreJanela(new ControleEstoque(prod, ex), 0);
    }//GEN-LAST:event_op_EstoqueActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bar_Principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu op_Acoes;
    private javax.swing.JMenu op_Arquivos;
    private javax.swing.JMenu op_Cadastros;
    private javax.swing.JMenuItem op_Cliente;
    private javax.swing.JMenuItem op_Estoque;
    private javax.swing.JMenuItem op_Fornecedor;
    private javax.swing.JMenuItem op_Funcionarios;
    private javax.swing.JMenuItem op_Pedido;
    private javax.swing.JMenuItem op_Produtos;
    private javax.swing.JMenuItem op_Venda;
    // End of variables declaration//GEN-END:variables
}
